// ============================================================
// siteData.ts — AUTO-GENERATED by site_generator.py
// Do not edit manually. Re-run the generator to update.
// ============================================================

export type Variant = 'A' | 'B' | 'C' | 'D'

export interface ServiceItem {
  iconName: string
  name: string
  description: string
}

export interface ReviewItem {
  name: string
  rating: number
  text: string
  date: string
}

export interface WhyUsPoint {
  heading: string
  body: string
}

export interface ProcessStep {
  heading: string
  body: string
}

export interface FAQItem {
  question: string
  answer: string
}

export interface SiteData {
  businessName: string
  trade: string
  tagline: string
  phone: string
  email: string
  address: string
  city: string
  serviceArea: string
  googleBusinessUrl: string
  yearsExperience: number
  bookingUrl?: string
  variant: Variant
  hero: {
    heading: string
    subheading: string
    primaryCta: string
    secondaryCta: string
  }
  services: ServiceItem[]
  trustItems: string[]
  whyUs: {
    heading: string
    subheading: string
    points: WhyUsPoint[]
  }
  process: ProcessStep[]
  faqs: FAQItem[]
  reviews: ReviewItem[]
  seo: {
    title: string
    description: string
    canonicalUrl: string
  }
}

const siteData: SiteData = {
  businessName: 'Manchester & Ashton Roofing Co.Ltd',
  trade: 'Roofers',
  tagline: 'Manchester\'s Trusted Roofing Experts Since 2002',
  phone: '+44 161 370 6571',
  email: 'manchesterroofing@freeolamail.com',
  address: '1353 Ashton Old Rd, Openshaw, Manchester M11 1JT, United Kingdom',
  city: 'Manchester',
  serviceArea: 'Manchester',
  googleBusinessUrl: 'https://maps.google.com',
  yearsExperience: 20,

  variant: 'A',

  hero: {
    heading: 'Professional Roofers Serving Manchester for Over 20 Years',
    subheading: 'Manchester & Ashton Roofing Co. Ltd provides reliable roofing services across Manchester. With 22 years of experience and 47 five-star reviews, we\'re the local roofing company you can trust.',
    primaryCta: 'Get a Free Quote',
    secondaryCta: 'Call Now',
  },

  services: [
    {
      iconName: 'Roof',
      name: 'Roof Repairs',
      description: 'Quick and reliable repairs for leaking roofs, damaged tiles, and storm damage. We fix all types of roofing problems to keep your property dry and secure.',
    },
    {
      iconName: 'RefreshCw',
      name: 'Roof Replacement',
      description: 'Complete roof replacement using high-quality materials and expert craftsmanship. We handle everything from removing old roofing to installing your brand new roof.',
    },
    {
      iconName: 'Shield',
      name: 'Flat Roofing',
      description: 'Specialist flat roof installation and repair services for commercial and residential properties. We use modern materials to ensure long-lasting waterproof protection.',
    },
    {
      iconName: 'Droplets',
      name: 'Gutter Services',
      description: 'Professional gutter cleaning, repair, and replacement to protect your property from water damage. We ensure proper drainage to keep your roof and walls safe.',
    },
    {
      iconName: 'Search',
      name: 'Roof Inspections',
      description: 'Thorough roof surveys to identify potential problems before they become costly repairs. We provide detailed reports and honest advice on your roof\'s condition.',
    },
    {
      iconName: 'Hammer',
      name: 'Chimney Repairs',
      description: 'Expert chimney pointing, repairs, and maintenance to keep your chimney safe and weatherproof. We fix leaks, damaged brickwork, and structural issues.',
    },
  ],

  trustItems: [
    '22+ Years Experience',
    '4.5 Star Rating',
    'Fully Insured',
    'Free Quotes'
  ],

  whyUs: {
    heading: 'Why Choose Manchester & Ashton Roofing Co. Ltd?',
    subheading: 'We\'ve been protecting Manchester homes and businesses for over two decades. Our local expertise and commitment to quality work has earned us an excellent reputation.',
    points: [
      {
        heading: 'Local Experts',
        body: 'Based in Manchester, we know the local weather challenges and building styles. Our team lives and works in the community we serve.',
      },
      {
        heading: 'Quality Materials',
        body: 'We only use high-grade roofing materials from trusted suppliers. All our work comes with comprehensive guarantees for your peace of mind.',
      },
      {
        heading: 'Honest Pricing',
        body: 'No hidden costs or surprise charges. We provide detailed written quotes and stick to our agreed prices throughout the project.',
      },
      {
        heading: 'Fully Insured',
        body: 'Complete public liability insurance and all necessary certifications. You can trust us to work safely and professionally on your property.',
      },
    ],
  },

  process: [
    {
      heading: 'Contact Our Team',
      body: 'Call us or request a free quote online. We\'ll discuss your roofing needs and arrange a convenient time to visit your property.',
    },
    {
      heading: 'Free Survey',
      body: 'Our experienced roofer will inspect your roof and provide honest advice. You\'ll receive a detailed written quote with no obligation.',
    },
    {
      heading: 'Quality Work',
      body: 'Once you approve the quote, we\'ll complete the work to the highest standards. We keep disruption to a minimum and clean up afterwards.',
    },
    {
      heading: 'Guaranteed Results',
      body: 'All work is guaranteed and we\'re always available for aftercare. We stand behind our workmanship and use only quality materials.',
    },
  ],

  faqs: [
    {
      question: 'How quickly can you fix a leaking roof?',
      answer: 'We offer emergency roof repairs and aim to attend urgent leaks within 24 hours. For non-emergency repairs, we typically complete most jobs within a few days of your call.',
    },
    {
      question: 'Do you provide free quotes?',
      answer: 'Yes, all our quotes are completely free with no obligation. We\'ll visit your property, assess the work needed, and provide a detailed written estimate.',
    },
    {
      question: 'Are you fully insured?',
      answer: 'Absolutely. We carry full public liability insurance and all necessary trade certifications. You can request copies of our insurance documents if needed.',
    },
    {
      question: 'What areas of Manchester do you cover?',
      answer: 'We cover all areas of Manchester and surrounding districts. Based in Openshaw, we\'re perfectly positioned to serve customers across the Greater Manchester area.',
    },
    {
      question: 'How long do roof repairs take?',
      answer: 'Most standard repairs can be completed in a day. Larger jobs like full roof replacement may take several days depending on the size and complexity of your roof.',
    },
    {
      question: 'Do you guarantee your work?',
      answer: 'Yes, all our roofing work comes with comprehensive guarantees. We use quality materials and stand behind our workmanship to give you complete peace of mind.',
    },
  ],

  reviews: [
    {
      name: 'Sarah M',
      rating: 5,
      text: 'Excellent service from start to finish. They fixed our leaking roof quickly and the price was very reasonable. Would definitely recommend to others in Manchester.',
      date: 'October 2024',
    },
    {
      name: 'David R',
      rating: 5,
      text: 'Professional team who turned up on time and completed the work to a high standard. Our new roof looks brilliant and hasn\'t leaked once since.',
      date: 'September 2024',
    },
    {
      name: 'Lisa K',
      rating: 5,
      text: 'Very honest and reliable roofers. They could have charged us for a full replacement but instead repaired what was needed. Great local company.',
      date: 'August 2024',
    },
  ],

  seo: {
    title: 'Manchester & Ashton Roofing Co.Ltd | Roofers in Manchester',
    description: 'Professional roofers in Manchester with 22+ years experience. Roof repairs, replacement & maintenance. Free quotes. Call +44 161 370 6571 today.',
    canonicalUrl: 'https://preview-manchester-ashton-roofing-coltd.vercel.app',
  },
}

export default siteData

// CSS custom properties injected by site_generator.py
// These override :root variables in index.css at runtime
export const siteTheme = {
  '--color-primary':  '#1B2D45',
  '--color-accent':   '#E85D26',
  '--color-bg':       '#FAFAF8',
  '--color-text':     '#1A1A1A',
  '--color-muted':    '#6B7280',
  '--color-border':   '#E5E5E5',
  '--font-heading':   "'Instrument Serif', Georgia, serif",
  '--font-body':      "'DM Sans', system-ui, sans-serif",
}
